sudo: required
services:
  - docker
before_install:
  - docker build -t mdshoaibalam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mdshoaibalam/docker-react npm run test
  
language: generic
