sudo: required
services:
  - docker
before_install:
  - docker build -t mdshoaibalam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mdshoaibalam/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-reactJs"
  env: "DockerReactjs-env"
  bucker_name: "elasticbeanstalk-us-east-2-450307943118"
  bucket_path: "docker-reactJs"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY